Cinema/Controllers/AdminController.cs
using Cinema.Data;
using Cinema.Models.UserAccounts;
using Cinema.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Cinema.Models.AdminPanel;
using Cinema.Models.Utilities;
using static Cinema.Models.MovieHall;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Cinema.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult AdminPanel()
        {
            AdminPanel AdminPanelViewModel = new AdminPanel();
            AdminPanelViewModel.Movie = _db.Movie.Take(3).ToList();

            return View(AdminPanelViewModel);
        }

        public IActionResult MovieHall()
        {
            IEnumerable<MovieHall> MovieHall = _db.MovieHall.Where(x=>x.MallCode==LoginInfo.BranchCode).ToList();

            return View(MovieHall);
        }
        [HttpGet]
        public IActionResult AddMovieHall()
        {
            MovieHall MovieHall = new MovieHall();
            string methodName = nameof(AddMovieHall);
            ViewBag.MethodName = methodName;
            ViewData["Title"] = "Add Movie Hall";
            return PartialView("_ManageMovieHallPartial", MovieHall);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult AddMovieHall(MovieHall movieHall)
        {
            ModelState.Remove("MallCode");
            movieHall.MallCode = LoginInfo.BranchCode;
            movieHall.HallCode = $"{LoginInfo.BranchCode}{Utility.GenerateString(3)}{movieHall.SelHallCode}";
            movieHall.MallName = _db.CinemaBranch.Where(x => x.MallCode == LoginInfo.BranchCode).Select(x => x.MallName).FirstOrDefault();
            _db.MovieHall.Add(movieHall);
            _db.SaveChanges();
            return Json(new { success = true, message = "Movie hall added successfully", movieId = movieHall.Id });
            //var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
            //return Json(new { success = false, errors });

        }


        #region Manage Cinema Hall -> Lead into Manage Movie Show filter by Date order by ShowTime 

        [HttpGet]
        public IActionResult ManageHall(string HallCode)
        {
            var movieHall = _db.MovieHall.FirstOrDefault(x => x.HallCode == HallCode);

            if (movieHall == null)
            {
                return NotFound();
            }
            movieHall.MovieShowTimes = _db.MovieShowTimes.Where(x=>x.HallCode == HallCode).ToList();
            //MovieHall MovieHall = new MovieHall();
            string methodName = nameof(ManageHall);
            ViewBag.MethodName = methodName;
            ViewData["Title"] = "Manage Hall";
            return View(movieHall);
        }

        [HttpGet]
        public IActionResult FilterHall()
        {
            FilterHallModel model = new FilterHallModel();
            string methodName = nameof(FilterHall);
            ViewBag.MethodName = methodName;
            ViewData["Title"] = "Filter By";
            return PartialView("_FilterHall", model);
        }

        [HttpGet]
        public IActionResult AddMovieShow(int id, DateTime DefaultDate, string HallCode)
        {
            MovieShowTime model = OnInitAddMovieShow(DefaultDate, HallCode);
            string methodName = nameof(AddMovieShow);
            ViewBag.MethodName = methodName;
            ViewData["Title"] = "Add Show Time";
            return PartialView("_ManageShowTimePartial", model);
        }

        [HttpPost]
        public IActionResult AddMovieShow(MovieShowTime MovieShowTime)
        {
            if (!string.IsNullOrEmpty(MovieShowTime.MovieCode) && MovieShowTime.MovieCode.Length >= 5)
            {
                MovieShowTime.MovieCode = MovieShowTime.MovieCode.Substring(0, 6);
            }
            else
            {
                throw new Exception(Utility.PleaseContactAdmmin);
            }
            MovieShowTime.MovieShowTimeCode = MovieShowTime.BuildMovieShowTimeCode(_db);
            MovieShowTime.MallName = _db.CinemaBranch.Where(x => x.MallCode == LoginInfo.BranchCode).Select(x => x.MallName).FirstOrDefault();
            MovieShowTime.MovieName = _db.Movie.Where(x => x.MovieCode == MovieShowTime.MovieCode).Select(x => x.Name).FirstOrDefault();
            _db.MovieShowTimes. Add(MovieShowTime);
            _db.SaveChanges();
            return Json(new { success = true, message = "Movie hall added successfully" });

        }

        public MovieShowTime OnInitAddMovieShow(DateTime Date, string HallCode)
        {
            var model = new MovieShowTime
            {
                StartTime = Utility.RoundToNearestFiveMinutes(Date),
                EndTime = Utility.RoundToNearestFiveMinutes(Date.AddHours(2)),
                MovieSelections = _db.Movie.Select(x => $"{x.MovieCode} - {x.Name}").ToList(),
                HallCode = HallCode
            };
            return model;
        }


        #endregion

        #region Old Design - Manual Partial View

        //Dynamic Partial View
        [HttpGet]
        public IActionResult LoadPartial(string partial)
        {
            try
            {
                string? typeName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name + ".Models." + partial;

                Type? entityType = Type.GetType(typeName);

                if (entityType == null)
                {
                    return PartialView($"_{partial}");
                }
                else
                {
                    //Dynamic Rendering
                    string entitySetName = _db.Model.FindEntityType(entityType).GetTableName();

                    var dbSetProperty = _db.GetType().GetProperty(entitySetName);

                    var dbSet = dbSetProperty.GetValue(_db);

                    IEnumerable<object> entityList = (IEnumerable<object>)dbSet;

                    //Process
                    //IEnumerable<object> processedEntities = ProcessEntities(entityList, entityType);

                    return PartialView($"{partial}", entityList);
                }

            }
            catch (Exception)
            {
                throw new Exception("Error, Please contact your administrator!");
            }

        }

        private IEnumerable<object> ProcessEntities(IEnumerable<object> entities, Type entityType)
        {
            return entityType switch
            {
                var type when type == typeof(MovieHall) => entities.Cast<MovieHall>()
                    .OrderBy(x => x.ExternalCode.Substring(0, 1))
                    .ThenBy(x => int.Parse(x.ExternalCode.Substring(1)))
                    .Cast<object>(),

                var type when type == typeof(Movie) => entities.Cast<Movie>()
                    .OrderByDescending(x => x.MovieCode)
                    .Cast<object>(),

                _ => entities
            };
        }

        #endregion

    }
}

Cinema/Controllers/CinemaBranchController.cs
using Cinema.Data;
using Cinema.Models;
using Cinema.Models.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace Cinema.Controllers
{
    public class CinemaBranchController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CinemaBranchController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult CinemaBranch()
        {
            IEnumerable<CinemaBranch> CinemaBranchList = _db.CinemaBranch;
            return View(CinemaBranchList);
        }

        [HttpGet]
        public IActionResult CreateCinemaBranch()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCinemaBranch(CinemaBranch cinemaBranch)
        {

            try
            {
                ModelState.Remove("MallCode");
                if (ModelState.IsValid)
                {
                    string? latestMallCode = _db.CinemaBranch.OrderByDescending(x => EF.Property<DateTime>(x, "CreatedDateTime")).Select(x => x.MallCode).FirstOrDefault();
                    if (!string.IsNullOrEmpty(latestMallCode))
                    {
                        // Extract the numeric portion from the latest MallCode
                        string numericPart = Regex.Replace(latestMallCode, "[^0-9]", ""); //Remove Characters

                        // Parse the numeric portion to an integer and increment it
                        if (int.TryParse(numericPart, out int numericValue))
                        {
                            numericValue++; // Increment the numeric value
                            string newNumericPart = numericValue.ToString().PadLeft(3, '0'); // Convert back to string and pad with leading zeros if necessary

                            // Construct the new MallCode
                            cinemaBranch.MallCode = latestMallCode.Substring(0, latestMallCode.Length - 3) + newNumericPart;
                            ImageUtility.SaveImageFile(cinemaBranch);
                            _db.CinemaBranch.Add(cinemaBranch);
                            _db.SaveChanges();
                            return RedirectToAction("CreateCinemaBranch");
                        }
                        else
                        {
                            throw new Exception("Please contact your administrator.");
                        }
                    }
                }
                return View();

            }
            catch (Exception ex)
            {
                throw new Exception("Error Creating Cinema");
            }

        }
        [HttpGet]
        public IActionResult BuyTicket()
        {
            return View();
        }
    }
}

Cinema/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Cinema.Data;
using Cinema.Models;
using Cinema.Models.Utilities;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Identity;
using static Cinema.Models.Account;

namespace Cinema.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;

        public LoginController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Account LoginAttempt)
        {

            try
            {
                var user = _db.Account.FirstOrDefault(x => x.UserName == LoginAttempt.UserName);

                if (user != null && Security.VerifyPassword(user.Password, LoginAttempt.Password))
                {
                    LoginInfo.SetLoginInfo(user.AccountType, user.UserName, user.UserToken);

                    //Check if its BranchManager
                    if(!string.IsNullOrEmpty(LoginInfo.RoleType) && LoginInfo.RoleType == AccountTypeSelections.BranchManager.ToString())
                    {
                        string branchToken = _db.BranchManager.Where(x=>x.UserToken==LoginInfo.UserToken).Select(y=>y.BranchCode).FirstOrDefault();
                        LoginInfo.SetBranchManager(branchToken);
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid email or password.");
                    throw new Exception("Wrong Password");
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error Login");
            }

        }

    }
}

Cinema/Views/Shared/_Layout.cshtml
@{
    string roleType = LoginInfo.RoleType;
}
@using  Cinema.Models.Utilities
@using Cinema.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Ember - CMS</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="~/css/assets/img/EmberIcon-S.png" rel="icon">
    <link href="~/css/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="~/css/assets/vendor/aos/aos.css" />
    <link rel="stylesheet" href="~/css/assets/vendor/aos/aos.css">
    <link rel="stylesheet" href="~/css/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/assets/vendor/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/assets/vendor/glightbox/css/glightbox.min.css">
    <link rel="stylesheet" href="~/css/assets/vendor/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

    <!-- Template Main CSS File -->
    <link href="~/css/assets/css/style.css" rel="stylesheet">
    <link href="~/css/bootswatch.css" rel="stylesheet"/>

    <!-- =======================================================
    * Template Name: TheEvent
    * Updated: Feb 06 2024 with Bootstrap v5.3.2
    * Template URL: https://bootstrapmade.com/theevent-conference-event-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->

    <!--SideBAR-->
@*    <link href="~/css/assets/css/sidebar.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600&display=swap" rel="stylesheet">*@



</head>
<body>

@*        <aside class="sidebar">
            <div class="toggle">
                <a href="#" class="burger js-menu-toggle" data-toggle="collapse" data-target="#main-navbar">
                    <span></span>
                </a>
            </div>
            <div class="side-inner">

                <div class="profile">
                    <img src="images/person_4.jpg" alt="Image" class="img-fluid">
                    <h3 class="name">Craig David</h3>
                    <span class="country">Web Designer</span>
                </div>


                <div class="nav-menu">
                    <ul>
                        <li class="accordion">
                            <a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" class="collapsible">
                                <span class="icon-home mr-3"></span>Feed
                            </a>
                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne">
                                <div>
                                    <ul>
                                        <li><a href="#">News</a></li>
                                        <li><a href="#">Sport</a></li>
                                        <li><a href="#">Health</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="accordion">
                            <a href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="collapsible">
                                <span class="icon-search2 mr-3"></span>Explore
                            </a>

                            <div id="collapseTwo" class="collapse" aria-labelledby="headingOne">
                                <div>
                                    <ul>
                                        <li><a href="#">Interior</a></li>
                                        <li><a href="#">Food</a></li>
                                        <li><a href="#">Travel</a></li>
                                    </ul>
                                </div>
                            </div>

                        </li>
                        <li><a href="#"><span class="icon-notifications mr-3"></span>Notifications</a></li>
                        <li><a href="#"><span class="icon-location-arrow mr-3"></span>Direct</a></li>
                        <li><a href="#"><span class="icon-pie-chart mr-3"></span>Stats</a></li>
                        <li><a href="#"><span class="icon-sign-out mr-3"></span>Sign out</a></li>
                    </ul>
                </div>
            </div>

        </aside>*@
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/css/assets/img/EmberIcon-S.png" alt="Icon" style="width: 50px; height: 50px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Cinemas"><i class="fa-solid fa-clapperboard nav-icon"></i>Cinemas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Cinemas"><i class="fa-solid fa-rectangle-ad nav-icon"></i>Promotions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminPanel"><i class="fa-solid fa-user-secret nav-icon"></i>Admin Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="UserAccounts" asp-action="UserAccounts"><i class="fa-solid fa-users-gear nav-icon"></i>Manage User</a>
                        </li>
                        @if (roleType == Account.AccountTypeSelections.Admin.ToString())
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="Movie"><i class="fas fa-film nav-icon"></i>Movies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Movie" asp-action="ManageMovie"><i class="fa-solid fa-video nav-icon"></i>Manage Movies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="UserAccounts" asp-action="UserAccounts"><i class="fa-solid fa-users-gear nav-icon"></i>Manage User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminPanel"><i class="fa-solid fa-user-secret nav-icon"></i>Admin Panel</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa-solid fa-shop-lock nav-icon"></i>Manage Cinemas</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link" asp-area="" asp-controller="CinemaBranch" asp-action="CinemaBranch">Cinema Branch</a>
                                    <a class="nav-link" asp-area="" asp-controller="CinemaBranch" asp-action="CinemaBranch">Manage Branch Hall</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <a class="btn btn-primary" asp-area="" asp-controller="Login" asp-action="@(!LoginInfo.IsLoggedIn ? "Login" : "Logout")">@(!LoginInfo.IsLoggedIn ? "Login" : "Logout")</a>
                    </form>
                </div>
            </div>
        </nav>

    <div class="container-fluid" style="padding-left: 0; padding-right: 0;">
        <main role="main">
    @RenderBody()
        </main>
    </div>

@*    <main>
        <div class="site-section">
            <div class="container">
                <div class="row justify-content-center">
                    @RenderBody()
                </div>
            </div>
        </div>
    </main>*@

    <footer class="border-top footer" style="background-color: rgb(223, 105, 25); position: fixed; bottom: 0; width: 100%;">
        <div class="container">
            &copy; 2024 - Cinema - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>